/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wrestlingstopwatch;

//import stopwatch.NewJFrame1;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.concurrent.ExecutorService;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
//import static stopwatch.NewJFrame1.OPTIMAL_TIME;

/**
 *
 * @author tharu
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private DecimalFormat numFormat = new DecimalFormat();//the display format, set so the text field displays a number with 2 decimal places
    
     static final int FPS = 100; //fps of the game loop or amount of updates a second
    static final long OPTIMAL_TIME = 1000000000 / FPS;//sets the amount of time each loop should take
    private boolean countStart = true;//true if the count down has started
	private boolean countOver = true;//true just for a brief moment when the counter hits 0
	private double counter=60;//the stop watch counter, will be dropped 1.0 a second when the stop watch is started
        private boolean clicked = false;
        private int minutes;
        private boolean running = true;//if made false the game loop will end
        private boolean NewRunning = false;
        private boolean PausedPressed = false;
        private boolean StopPressed = false;
        private boolean RedPressed = false;
        private boolean BluePressed = false;
    
        /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
       
        initComponents();
        setIcon();
        setVisible(true);
                 jLabel3.setText("");
                 jRadioButton3.setSelected(true);
        TheStopWatchFunc();
        
         //new NewJFrame().setVisible(true);
//        this.setVisible(true);
        //jLabel1.setText("Hello");
                //makeGui();//lays out the initial states of the swing components before the game loop takes over
		//repaint();//this stops the GUI from doing weird stuff
        //numFormat.applyPattern("0.00");	
        //jLabel1.setText(numFormat.format(counter));
        //jLabel1.setText("HAi");
    }
    
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
//        new NewJFrame().setVisible(true);
           new NewJFrame();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NewJFrame1().setVisible(true);
                
            }
        });
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setText("00.00");
        jLabel1.setToolTipText("");

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 250)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setLabelFor(jLabel1);
        jLabel2.setText("6");

        jButton2.setText("PAUSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("STOP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel3.setText("Caution");

        jRadioButton1.setText("RED");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("BLUE");
        jRadioButton2.setToolTipText("");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("NONE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 247, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: The Start Button
        if(StopPressed){
         NewRunning = true;
         PausedPressed = false;
          StopPressed = false;
        counter = 60;
        minutes = 6;
        jLabel2.setText("6");
        }
        else if(PausedPressed){
         NewRunning = true;
         PausedPressed = false;
          StopPressed = false;
        }
        else{
             PausedPressed = false;
          StopPressed = false;   
        NewRunning = true;  
        counter = 60;
        minutes = 6;
        jLabel2.setText("6");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: The Stop Button
        StopPressed = true;
         NewRunning = false;  
         PausedPressed=false;
        counter = 60;
        minutes = 6;
        jLabel2.setText("Over");
         numFormat.applyPattern("0.00");	
                
                jLabel1.setText(numFormat.format(0));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: The Pause Button
        NewRunning = false; 
        PausedPressed = true;
//        StopPressed = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
         jRadioButton3.setSelected(false);
        RedPressed = true;
        BluePressed = false;
        jLabel3.setText("RED caution");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
         jRadioButton3.setSelected(false);
        BluePressed = true;
        RedPressed = false;
        jLabel3.setText("BLUE caution");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
         jRadioButton1.setSelected(false);
        jLabel3.setText("");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        //TheWindow.printText(456215);
////        clicked = true;
//       TheStopWatchFunc();
//    }      
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new NewJFrame().setVisible(true);
////            }
////        });
//        
//        //new NewJFrame(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables

    public void printText(double counter){
        repaint();
    numFormat.applyPattern("0.00");	
    jLabel1.setText(numFormat.format(counter));
    }
    

// Note you must use final method arguments to be available inside an anonymous class
public void changeJLabel(final double text) {
  EventQueue.invokeLater(new Runnable() {
      
      //numFormat.applyPattern("0.00");	
    
    
    @Override
    public void run() {
      jLabel1.setText(numFormat.format(text));
    }
  });
}

public void TheStopWatchFunc(){
 //START
        // running = true;
        long lastLoopTime = System.nanoTime();//used in the loop
		while(running)//my awesome game loop, it's smooth and simple. there are better game loops but I like this one
		{
                    
                      long now = System.nanoTime();//now = the current time in nanoseconds
    	        long updateLength = now - lastLoopTime;//updateLength = difference between the last loop's time and the current time
    	        lastLoopTime = now;
                
    		 if(NewRunning){
                if(counter <= 0)
                {
                    if(minutes<=0){
                      counter = 0;//in case the counter dips below 1 it is now made to be zero.
                      minutes=0;
                        countStart = false;
                        countOver = true;
                        NewRunning=false;
                        numFormat.applyPattern("0.00");	
                jLabel2.setText("Over");
                jLabel1.setText(numFormat.format(counter));
                    }if(minutes==4){
                     jLabel2.setText("Break");
                     NewRunning = true;  
                    counter = 30;
                     minutes = minutes - 1;
                    }
                    else{
                    NewRunning = true;  
                    counter = 60;
                    minutes = minutes - 1;
                    numFormat.applyPattern("0");	
                     jLabel2.setText(numFormat.format(minutes));
                    }
                      
                }
                //this.printText(counter);
                
                 //repaint();
               
                  
    	        double delta = updateLength / ((double)OPTIMAL_TIME);

                counter -= delta*.01;//delta*.01 will subtract 1.0 a second from the counter
                //repaint();
                
                 numFormat.applyPattern("0.00");	
                jLabel1.setText(numFormat.format(counter));
                System.out.println(counter);
                }
   
    
//                TheWindow.changeJLabel(counter);
    	        //paintGui();
                
    	    
    	        try{Thread.sleep((lastLoopTime-System.nanoTime())/1000000 + 10 );}
    	        catch(Exception ex){}//this catch is thrown every once and a while but that does not matter much
		}   
        //END
}

    private void setIcon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("stopwatch2.png")));
        
    }

}
